# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField(auto_now_add=True)),
                ('chekout', models.DateField()),
                ('pricemin', models.IntegerField()),
                ('pricemax', models.IntegerField()),
            ],
        ),
    ]
